language: ruby
dist: xenial
cache: bundler

addons:
  apt:
    packages:
    - bind9

before_script:
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

after_success:
  - unset COVERAGE
  - bundle exec rake external

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: 2.6
      gemfile: gems/event.gemfile
    - rvm: 2.6
      env: COVERAGE=PartialSummary,Coveralls
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: ruby-head-scheduler --url https://github.com/ioquatix/ruby.git --branch thread-selector
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: jruby-head
